# Example usage of Activation functions
**List of available activation functions and their gradients in `activation.py`, as well as how to use them.**

## Run the following for Google colab 
then restart runtime

In [ ]:
! pip install --upgrade --no-cache-dir https://github.com/manassharma07/crysx_nn/tarball/main
! pip install IPython==7.7.0

## Using CPU

In [1]:
import numpy as np
np.random.seed(0)

### Sigmoid

In [2]:
import crysx_nn.activation as activation
import numpy as np
# inputs should be a 2d array where the rows correspond to the samples and the columns correspond to the nodes.
inputs = np.random.random((5,4)) # BatchSize=nSamples=5; nodes=4
output = activation.Sigmoid(inputs)
gradient_wrt_inputs = activation.Sigmoid_grad(inputs)
print('Output\n',output)
print('Gradient\n',gradient_wrt_inputs)

Output
 [[0.63386027 0.6715468  0.64628827 0.63294764]
 [0.60435748 0.65608461 0.60768396 0.70925592]
 [0.72385455 0.59470289 0.68820161 0.62922533]
 [0.63831185 0.71618109 0.51775155 0.52176856]
 [0.50505443 0.6969086  0.68528272 0.70474823]]
Gradient
 [[0.23208143 0.22057169 0.22859974 0.23232493]
 [0.23910952 0.22563759 0.23840416 0.20621196]
 [0.19988914 0.24103136 0.21458015 0.23330081]
 [0.23086983 0.20326574 0.24968488 0.24952613]
 [0.24997445 0.211227   0.21567032 0.20807816]]


### Tanh

In [3]:
import crysx_nn.activation as activation
import numpy as np
# inputs should be a 2d array where the rows correspond to the samples and the columns correspond to the nodes.
inputs = np.random.random((5,4)) # BatchSize=nSamples=5; nodes=4
output = activation.Tanh(inputs)
gradient_wrt_inputs = activation.Tanh_grad(inputs)
print('Output\n',output)
print('Gradient\n',gradient_wrt_inputs)

Output
 [[0.75246717 0.6635661  0.43128916 0.65301033]
 [0.11772599 0.56484577 0.14237931 0.73736002]
 [0.47912529 0.3924239  0.25855159 0.64938453]
 [0.42694144 0.51420823 0.01878759 0.54947958]
 [0.54560065 0.54898969 0.73693956 0.59270151]]
Gradient
 [[0.43379315 0.55968003 0.81398966 0.5735775 ]
 [0.98614059 0.68094925 0.97972813 0.45630019]
 [0.77043895 0.84600348 0.93315108 0.57829974]
 [0.81772101 0.73558989 0.99964703 0.69807219]
 [0.70231993 0.69861032 0.45692008 0.64870492]]


### Tanh_offset

In [4]:
import crysx_nn.activation as activation
import numpy as np
# inputs should be a 2d array where the rows correspond to the samples and the columns correspond to the nodes.
inputs = np.random.random((5,4)) # BatchSize=nSamples=5; nodes=4
output = activation.Tanh_offset(inputs)
gradient_wrt_inputs = activation.Tanh_offset_grad(inputs)
print('Output\n',output)
print('Gradient\n',gradient_wrt_inputs)

Output
 [[0.67239025 0.70559061 0.80143103 0.53007638]
 [0.79142451 0.79269966 0.60366632 0.56410834]
 [0.65268369 0.67423919 0.75775189 0.70624228]
 [0.87833404 0.55084604 0.60294556 0.5799624 ]
 [0.78687938 0.62400516 0.71760684 0.61983576]]
Gradient
 [[0.4405632  0.415465   0.31827867 0.49819082]
 [0.33014352 0.32865382 0.47850659 0.49178024]
 [0.45337538 0.43928141 0.36712793 0.41492824]
 [0.21372672 0.49482936 0.47880442 0.48721203]
 [0.33540045 0.46924544 0.40529453 0.47127878]]


### Identity

In [5]:
import crysx_nn.activation as activation
import numpy as np
# inputs should be a 2d array where the rows correspond to the samples and the columns correspond to the nodes.
inputs = np.random.random((5,4)) # BatchSize=nSamples=5; nodes=4
output = activation.Identity(inputs)
gradient_wrt_inputs = activation.Identity_grad(inputs)
print('Output\n',output)
print('Gradient\n',gradient_wrt_inputs)

Output
 [[0.15896958 0.11037514 0.65632959 0.13818295]
 [0.19658236 0.36872517 0.82099323 0.09710128]
 [0.83794491 0.09609841 0.97645947 0.4686512 ]
 [0.97676109 0.60484552 0.73926358 0.03918779]
 [0.28280696 0.12019656 0.2961402  0.11872772]]
Gradient
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### ReLU

In [6]:
import crysx_nn.activation as activation
import numpy as np
# inputs should be a 2d array where the rows correspond to the samples and the columns correspond to the nodes.
inputs = np.random.random((5,4)) # BatchSize=nSamples=5; nodes=4
output = activation.ReLU(inputs)
gradient_wrt_inputs = activation.ReLU_grad(inputs)
print('Output\n',output)
print('Gradient\n',gradient_wrt_inputs)

Output
 [[0.31798318 0.41426299 0.0641475  0.69247212]
 [0.56660145 0.26538949 0.52324805 0.09394051]
 [0.5759465  0.9292962  0.31856895 0.66741038]
 [0.13179786 0.7163272  0.28940609 0.18319136]
 [0.58651293 0.02010755 0.82894003 0.00469548]]
Gradient
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Softplus

In [7]:
import crysx_nn.activation as activation
import numpy as np
# inputs should be a 2d array where the rows correspond to the samples and the columns correspond to the nodes.
inputs = np.random.random((5,4)) # BatchSize=nSamples=5; nodes=4
output = activation.Softplus(inputs)
gradient_wrt_inputs = activation.Softplus_grad(inputs)
print('Output\n',output)
print('Gradient\n',gradient_wrt_inputs)

Output
 [[1.08841802 0.83723666 1.12683903 1.28576066]
 [0.82523866 1.02215896 1.03235702 1.01966053]
 [0.81089582 1.27893952 0.94149457 1.20335046]
 [1.10283814 0.85288372 1.18064114 0.91092475]
 [1.22775599 1.02543685 1.228203   1.09820194]]
Gradient
 [[0.6632512  0.56709486 0.67594403 0.72355977]
 [0.56186958 0.64018273 0.64383352 0.63928263]
 [0.55554027 0.72166769 0.60995555 0.69981324]
 [0.66807231 0.57381584 0.69291821 0.59784784]
 [0.70705078 0.64136024 0.7071817  0.66652985]]


### Softmax

In [8]:
import crysx_nn.activation as activation
import numpy as np
# inputs should be a 2d array where the rows correspond to the samples and the columns correspond to the nodes.
inputs = np.random.random((5,4)) # BatchSize=nSamples=5; nodes=4
output = activation.Softmax(inputs)
jacobian_wrt_inputs = activation.Softmax_grad(inputs) 
print('Output\n',output)
print('Gradient\n',jacobian_wrt_inputs)

Output
 [[0.25119534 0.20079831 0.31641677 0.23158959]
 [0.26649876 0.31986779 0.17780861 0.23582485]
 [0.29046088 0.20061205 0.27847013 0.23045694]
 [0.18875797 0.22213246 0.29147564 0.29763393]
 [0.24815206 0.26851782 0.26822327 0.21510685]]
Gradient
 [[[ 0.18809626 -0.0504396  -0.07948241 -0.05817422]
  [-0.0504396   0.16047834 -0.06353595 -0.0465028 ]
  [-0.07948241 -0.06353595  0.21629721 -0.07327883]
  [-0.05817422 -0.0465028  -0.07327883  0.17795585]]

 [[ 0.19547716 -0.08524437 -0.04738577 -0.06284703]
  [-0.08524437  0.2175524  -0.05687525 -0.07543277]
  [-0.04738577 -0.05687525  0.14619271 -0.04193169]
  [-0.06284703 -0.07543277 -0.04193169  0.1802115 ]]

 [[ 0.20609337 -0.05826995 -0.08088468 -0.06693873]
  [-0.05826995  0.16036686 -0.05586446 -0.04623244]
  [-0.08088468 -0.05586446  0.20092452 -0.06417537]
  [-0.06693873 -0.04623244 -0.06417537  0.17734654]]

 [[ 0.1531284  -0.04192927 -0.05501835 -0.05618078]
  [-0.04192927  0.17278963 -0.0647462  -0.06611416]
  [-0.055018

## Using GPU

*** In order to use the GPU, replace the numpy arrays with cupy arrays. Also, use the `_cupy` suffix after all the activation function names.***

In [9]:
import cupy as cp
cp.random.seed(0)

### Sigmoid GPU

In [10]:
import crysx_nn.activation as activation
import cupy as cp
# inputs should be a 2d array where the rows correspond to the samples and the columns correspond to the nodes.
inputs = cp.random.random((5,4)) # BatchSize=nSamples=5; nodes=4
output = activation.Sigmoid_cupy(inputs)
gradient_wrt_inputs = activation.Sigmoid_grad_cupy(inputs)
print('Output\n',output)
print('Gradient\n',gradient_wrt_inputs)

Output
 [[0.60788984 0.61310069 0.56222935 0.6212233 ]
 [0.51324968 0.58363154 0.59790957 0.7056643 ]
 [0.61825941 0.51070831 0.62443465 0.65803499]
 [0.6254168  0.56569315 0.51299224 0.64083647]
 [0.59521253 0.71263483 0.65511965 0.57037936]]
Gradient
 [[0.23835978 0.23720823 0.24612751 0.23530491]
 [0.24982445 0.24300577 0.24041372 0.2077022 ]
 [0.23601471 0.24988533 0.23451602 0.22502494]
 [0.23427063 0.24568441 0.2498312  0.23016509]
 [0.24093457 0.20478643 0.22593789 0.24504675]]


### Tanh GPU

In [11]:
import crysx_nn.activation as activation
import cupy as cp
# inputs should be a 2d array where the rows correspond to the samples and the columns correspond to the nodes.
inputs = cp.random.random((5,4)) # BatchSize=nSamples=5; nodes=4
output = activation.Tanh_cupy(inputs)
gradient_wrt_inputs = activation.Tanh_grad_cupy(inputs)
print('Output\n',output)
print('Gradient\n',gradient_wrt_inputs)

Output
 [[0.57553054 0.04534073 0.39238007 0.05722523]
 [0.0814353  0.10527342 0.66435577 0.59922298]
 [0.73127392 0.74094491 0.13840816 0.33677763]
 [0.13772204 0.63270351 0.07732565 0.02832989]
 [0.42217611 0.59474599 0.36180122 0.24283991]]
Gradient
 [[0.6687646  0.99794422 0.84603788 0.99672527]
 [0.99336829 0.98891751 0.55863141 0.64093183]
 [0.46523845 0.45100063 0.98084318 0.88658083]
 [0.98103264 0.59968627 0.99402074 0.99919742]
 [0.82176733 0.64627721 0.86909988 0.94102878]]


### Tanh_offset GPU

In [12]:
import crysx_nn.activation as activation
import cupy as cp
# inputs should be a 2d array where the rows correspond to the samples and the columns correspond to the nodes.
inputs = cp.random.random((5,4)) # BatchSize=nSamples=5; nodes=4
output = activation.Tanh_offset_cupy(inputs)
gradient_wrt_inputs = activation.Tanh_offset_grad_cupy(inputs)
print('Output\n',output)
print('Gradient\n',gradient_wrt_inputs)

Output
 [[0.60074977 0.78696583 0.81558852 0.59095794]
 [0.78504055 0.77932533 0.81425887 0.50152872]
 [0.54162475 0.74238721 0.62745101 0.87634078]
 [0.60938242 0.85180104 0.53977932 0.51030514]
 [0.71812883 0.55455601 0.83499787 0.63796673]]
Gradient
 [[0.47969897 0.33530122 0.30080778 0.48345331]
 [0.33750376 0.34395472 0.30248273 0.49999533]
 [0.49653476 0.38249688 0.46751248 0.21673524]
 [0.47607097 0.25247205 0.49683521 0.49978761]
 [0.40483962 0.49404728 0.27555286 0.46193036]]


### Identity GPU

In [13]:
import crysx_nn.activation as activation
import cupy as cp
# inputs should be a 2d array where the rows correspond to the samples and the columns correspond to the nodes.
inputs = cp.random.random((5,4)) # BatchSize=nSamples=5; nodes=4
output = activation.Identity_cupy(inputs)
gradient_wrt_inputs = activation.Identity_grad_cupy(inputs)
print('Output\n',output)
print('Gradient\n',gradient_wrt_inputs)

Output
 [[0.88713763 0.56265382 0.98994989 0.24305214]
 [0.79833729 0.82992379 0.65200104 0.25202245]
 [0.54965062 0.40358132 0.10968819 0.81840714]
 [0.89731261 0.77122132 0.65229201 0.85391034]
 [0.42346823 0.95508329 0.33617054 0.13766885]]
Gradient
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### ReLU GPU

In [14]:
import crysx_nn.activation as activation
import cupy as cp
# inputs should be a 2d array where the rows correspond to the samples and the columns correspond to the nodes.
inputs = cp.random.random((5,4)) # BatchSize=nSamples=5; nodes=4
output = activation.ReLU_cupy(inputs)
gradient_wrt_inputs = activation.ReLU_grad_cupy(inputs)
print('Output\n',output)
print('Gradient\n',gradient_wrt_inputs)

Output
 [[0.79431636 0.29322598 0.19465283 0.90575521]
 [0.11151696 0.97737315 0.0126922  0.0922648 ]
 [0.92461427 0.41958712 0.76254932 0.81891984]
 [0.5680262  0.18148492 0.18446183 0.19445675]
 [0.78633179 0.26517155 0.28181817 0.35346627]]
Gradient
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Softplus GPU

In [15]:
import crysx_nn.activation as activation
import cupy as cp
# inputs should be a 2d array where the rows correspond to the samples and the columns correspond to the nodes.
inputs = cp.random.random((5,4)) # BatchSize=nSamples=5; nodes=4
output = activation.Softplus_cupy(inputs)
gradient_wrt_inputs = activation.Softplus_grad_cupy(inputs)
print('Output\n',output)
print('Gradient\n',gradient_wrt_inputs)

Output
 [[0.91885823 0.7639514  0.90132921 1.22007504]
 [1.06023752 0.99012625 1.01944036 0.84007467]
 [1.19242887 1.07606607 1.17177768 1.08993645]
 [0.91852043 1.04740561 0.87053652 0.74268934]
 [0.82406833 1.07234487 0.79248434 0.81008479]]
Gradient
 [[0.60102568 0.53417786 0.5939704  0.70479199]
 [0.65362647 0.62847022 0.6392032  0.56832171]
 [0.69651675 0.6590659  0.6901843  0.66376214]
 [0.60089089 0.6491532  0.58127316 0.52416748]
 [0.56135653 0.65779485 0.54728131 0.55517965]]


### Softmax GPU

In [16]:
import crysx_nn.activation as activation
import cupy as cp
# inputs should be a 2d array where the rows correspond to the samples and the columns correspond to the nodes.
inputs = cp.random.random((5,4)) # BatchSize=nSamples=5; nodes=4
output = activation.Softmax_cupy(inputs)
jacobian_wrt_inputs = activation.Softmax_grad_cupy(inputs) 
print('Output\n',output)
print('Gradient\n',jacobian_wrt_inputs)

Output
 [[0.25747275 0.32568587 0.17966864 0.23717274]
 [0.39069779 0.16193293 0.17038333 0.27698596]
 [0.2505234  0.17156289 0.30927165 0.26864207]
 [0.16106974 0.35203962 0.33389437 0.15299627]
 [0.19930776 0.43635135 0.18970979 0.1746311 ]]
Gradient
 [[[ 0.19118054 -0.08385524 -0.04625978 -0.06106552]
  [-0.08385524  0.21961458 -0.05851554 -0.07724381]
  [-0.04625978 -0.05851554  0.14738782 -0.0426125 ]
  [-0.06106552 -0.07724381 -0.0426125   0.18092183]]

 [[ 0.23805303 -0.06326684 -0.06656839 -0.1082178 ]
  [-0.06326684  0.13571066 -0.02759067 -0.04485315]
  [-0.06656839 -0.02759067  0.14135285 -0.04719379]
  [-0.1082178  -0.04485315 -0.04719379  0.20026474]]

 [[ 0.18776142 -0.04298052 -0.07747978 -0.06730112]
  [-0.04298052  0.14212907 -0.05305954 -0.04608901]
  [-0.07747978 -0.05305954  0.21362269 -0.08308337]
  [-0.06730112 -0.04608901 -0.08308337  0.19647351]]

 [[ 0.13512628 -0.05670293 -0.05378028 -0.02464307]
  [-0.05670293  0.22810773 -0.11754405 -0.05386075]
  [-0.053780