# Example usage of Loss functions
**List of available loss functions and their gradients in `loss.py`, as well as how to use them.**

## Using CPU

In [3]:
import numpy as np
np.random.seed(0)

### Mean Absolute Error (MSE_loss)

In [5]:
from crysx_nn.loss import MAE_loss, MAE_loss_grad
import numpy as np
# predictions and targets should be 2d arrays where the rows correspond to the samples and the columns correspond to the output nodes.
predictions = np.random.random((5,4)) # BatchSize=nSamples=5; nodes=4
targets = np.random.random((5,4)) # BatchSize=nSamples=5; nodes=4
error = MAE_loss(predictions, targets)
gradient_wrt_predictions = MAE_loss_grad(predictions, targets)
print('Error\n',error)
print('Gradient\n',gradient_wrt_predictions)

Error
 1.251971532065993
Gradient
 [[-0.25 -0.25  0.25 -0.25]
 [ 0.25  0.25  0.25 -0.25]
 [ 0.25 -0.25  0.25 -0.25]
 [ 0.25  0.25  0.25 -0.25]
 [-0.25  0.25 -0.25  0.25]]


## Using GPU

*** In order to use the GPU, replace the numpy arrays with cupy arrays. Also, use the `_cupy` suffix after all the activation function names.***

In [4]:
import cupy as cp
cp.random.seed(0)